services:
    alexandre_evc:
        class: Alexandre\EvcBundle\Service\EvcService
        arguments:
            url: 'https://evc.de/services/api_resellercredits.asp'
            api_id: ''
            username: ''
            password: ''
